### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-user-profile-avatar#135]

**Comment by ritakikani** [comment]
Currently we do not have this functionality finished, so please comment code of this entire section.

![image](https://github.com/user-attachments/assets/8394e7c6-2545-47b9-a799-d1c1b5a10690)

@RHSRSK -Done
Code is commented for this entire section

**Comment by ritakikani** [comment]
Need proper description for function in entire addon

![image](https://github.com/user-attachments/assets/ba73863f-bbe3-4399-bf9f-da7f649fe6fc)

@RHSRSK -Done
Update all the function description in comment

**Comment by ritakikani** [comment]
Please change below in entire plugin.

![image](https://github.com/user-attachments/assets/9b4148dd-787f-4e43-8d0c-09034ad24605)

@RHSRSK : Done
Removed prefix of all the default WordPress options

**Comment by ritakikani** [comment]
Please keep as it is, because this will not reflect for entire WP site.

![image](https://github.com/user-attachments/assets/2e6f495a-704d-4f86-9156-b641750a4314)

@RHSRSK : Done
Changes are done for prefix

**Comment by ritakikani** [comment]
These should be as it is as like old code, do not add wpupa_ because we are overriding default functionality of WP core.

![image](https://github.com/user-attachments/assets/d7ac1d4d-388a-43d8-aff0-731c4844203e)

![image](https://github.com/user-attachments/assets/6de6f05d-93db-4641-a606-00c2d22dac2c)

![image](https://github.com/user-attachments/assets/6132c456-f6ec-47fe-9f66-345a380bf034)

![image](https://github.com/user-attachments/assets/b4917405-5a84-4aec-bb8a-95a282690389)

![image](https://github.com/user-attachments/assets/3b6d109b-c373-4104-95f5-4fbfdd6b0e86)

![image](https://github.com/user-attachments/assets/8506b340-05bf-4559-b1d6-1119f8aba289)

![image](https://github.com/user-attachments/assets/b9260c6e-ee98-4cc7-8ea3-e8721b1d980a)

@RHSRSK : Done 
All this options for disable and delete comment is our custom options so after discussion with @ritakikani it is right so didn't changed the prefix.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now it is working fine.
So I closed the issue.
